//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CT.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CT.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find the property &apos;{0}&apos;.
        /// </summary>
        internal static string CannotFindCompositeModelProperty {
            get {
                return ResourceManager.GetString("CannotFindCompositeModelProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path to the Composite relative to the CompositeRoot.
        /// </summary>
        internal static string CompositePathToComposite {
            get {
                return ResourceManager.GetString("CompositePathToComposite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be {1}.
        /// </summary>
        internal static string CompositeRootModeParameterCannotBeNone {
            get {
                return ResourceManager.GetString("CompositeRootModeParameterCannotBeNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;Compositactic - &lt;!-- ct: context.CompositeRootConfiguration.CompositeRootType.Name --&gt;&lt;/title&gt;
        ///    &lt;script src=&quot;https://code.jquery.com/jquery-1.11.1.min.js&quot;&gt;&lt;/script&gt;
        ///    &lt;link href=&quot;https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css&quot; rel=&quot;stylesheet&quot; id=&quot;bootstrap-css&quot;&gt;
        ///    &lt;script src=&quot;https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js&quot;&gt;&lt;/script&gt;
        ///    &lt;script src=&quot;https://cdnjs.cloudflare.com/ajax/libs/event-sour [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string defaultHomeFile {
            get {
                return ResourceManager.GetString("defaultHomeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=\&quot;utf - 8\&quot;&gt;
        ///    &lt;title&gt;Not Found&lt;/title&gt;
        ///    &lt;link href=&quot;//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css&quot; rel=&quot;stylesheet&quot; id=&quot;bootstrap-css&quot; /&gt;
        ///&lt;/head&gt;
        ///    &lt;body&gt;
        ///        &lt;div class=&quot;jumbotron&quot;&gt;
        ///            &lt;div class=&quot;container&quot;&gt;
        ///                &lt;h1&gt;404 Not Found&lt;/h1&gt;
        ///            &lt;/div&gt;
        ///        &lt;/div&gt;
        ///        &lt;div class=&quot;container&quot;&gt;
        ///            &lt;p&gt;The file is not found: &lt;!-- ct: context.FileInfo.Name --&gt; - &lt;b&gt;&lt;!-- ct: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string defaultNotFoundPage {
            get {
                return ResourceManager.GetString("defaultNotFoundPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory &apos;{0}&apos; does not exist.
        /// </summary>
        internal static string DirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("DirectoryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The column name &apos;{0}&apos; is invalid.
        /// </summary>
        internal static string InvalidColumnName {
            get {
                return ResourceManager.GetString("InvalidColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The table name &apos;{0}&apos; is invalid.
        /// </summary>
        internal static string InvalidTableName {
            get {
                return ResourceManager.GetString("InvalidTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key [{0}] was not found.
        /// </summary>
        internal static string KeyNotFound {
            get {
                return ResourceManager.GetString("KeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1}.
        /// </summary>
        internal static string ListenerCompositeRootFormatString {
            get {
                return ResourceManager.GetString("ListenerCompositeRootFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composites must all be of the same type.
        /// </summary>
        internal static string MustAllBeSameCompositeType {
            get {
                return ResourceManager.GetString("MustAllBeSameCompositeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be of type {1}.
        /// </summary>
        internal static string MustBeOfType {
            get {
                return ResourceManager.GetString("MustBeOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not have a CompositeModel attribute.
        /// </summary>
        internal static string MustHaveCompositeModelAttribute {
            get {
                return ResourceManager.GetString("MustHaveCompositeModelAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataContractAttribute missing from type &apos;{0}&apos;.
        /// </summary>
        internal static string MustHaveDataContractAttribute {
            get {
                return ResourceManager.GetString("MustHaveDataContractAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeyPropertyAttribute missing from type &apos;{0}&apos;.
        /// </summary>
        internal static string MustHaveKeyPropertyAttribute {
            get {
                return ResourceManager.GetString("MustHaveKeyPropertyAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must have valid Session Token.
        /// </summary>
        internal static string MustHaveValidSessionToken {
            get {
                return ResourceManager.GetString("MustHaveValidSessionToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must implement {1}.
        /// </summary>
        internal static string MustImplementInterface {
            get {
                return ResourceManager.GetString("MustImplementInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column &apos;{0}&apos; must map to a single &apos;{1}&apos; property .
        /// </summary>
        internal static string MustMapToASingleProperty {
            get {
                return ResourceManager.GetString("MustMapToASingleProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to keyPropertyValueGenerationFunc must return a unique key value.
        /// </summary>
        internal static string MustReturnAUniqueKeyValue {
            get {
                return ResourceManager.GetString("MustReturnAUniqueKeyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both {0} and {1} must be non-null, or both must be null.
        /// </summary>
        internal static string MustSpecifyBothNonNullOrBothNull {
            get {
                return ResourceManager.GetString("MustSpecifyBothNonNullOrBothNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A vaild relative path is required, and must not be a reserved name or located in a previously specified endpoint directory .
        /// </summary>
        internal static string MustSupplyAValidRelativePath {
            get {
                return ResourceManager.GetString("MustSupplyAValidRelativePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid {0} typename is required.
        /// </summary>
        internal static string MustSupplyAValidTypeName {
            get {
                return ResourceManager.GetString("MustSupplyAValidTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid endpoint is required.
        /// </summary>
        internal static string MustSupplyValidEndpoint {
            get {
                return ResourceManager.GetString("MustSupplyValidEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A placeholder path is required for the &apos;{0}&apos; value.
        /// </summary>
        internal static string PlaceholderPathRequiredError {
            get {
                return ResourceManager.GetString("PlaceholderPathRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The placeholder&apos;s type &apos;{0}&apos; must have a {1} that can convert from {2}.
        /// </summary>
        internal static string PlaceholderValueConversionError {
            get {
                return ResourceManager.GetString("PlaceholderValueConversionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1} {2}.
        /// </summary>
        internal static string VersionInfoFormatString {
            get {
                return ResourceManager.GetString("VersionInfoFormatString", resourceCulture);
            }
        }
    }
}
