//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CT.Test.Presentation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CT.Test.Presentation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a new Cashier with default values.
        /// </summary>
        internal static string Cashier_CreateNewCashier {
            get {
                return ResourceManager.GetString("Cashier_CreateNewCashier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The acting authority of the Cashier.
        /// </summary>
        internal static string Cashier_CreateNewCashier_ParameterAuthority {
            get {
                return ResourceManager.GetString("Cashier_CreateNewCashier_ParameterAuthority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first and last name of the Cashier.
        /// </summary>
        internal static string Cashier_CreateNewCashier_ParameterName {
            get {
                return ResourceManager.GetString("Cashier_CreateNewCashier_ParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets the collection of Cashiers loaded for the Shop.
        /// </summary>
        internal static string Shop_AllCashiers {
            get {
                return ResourceManager.GetString("Shop_AllCashiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets the colleciton of Products loaded for the Shop.
        /// </summary>
        internal static string Shop_AllProducts {
            get {
                return ResourceManager.GetString("Shop_AllProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets the collection of Registers loaded for the Shop.
        /// </summary>
        internal static string Shop_AllRegisters {
            get {
                return ResourceManager.GetString("Shop_AllRegisters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the Shop&apos;s error message.
        /// </summary>
        internal static string Shop_ErrorMessage {
            get {
                return ResourceManager.GetString("Shop_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the name of the Shop.
        /// </summary>
        internal static string Shop_Name {
            get {
                return ResourceManager.GetString("Shop_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loads Cashier, Register, and Product data for the Shop.
        /// </summary>
        internal static string Shop_Setup {
            get {
                return ResourceManager.GetString("Shop_Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The id of the Shop to load.
        /// </summary>
        internal static string Shop_Setup_ParameterId {
            get {
                return ResourceManager.GetString("Shop_Setup_ParameterId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns 1 on success.
        /// </summary>
        internal static string Shop_Setup_ReturnValue {
            get {
                return ResourceManager.GetString("Shop_Setup_ReturnValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username and password.
        /// </summary>
        internal static string ShopMonitor_ShopMonitorAuthenticator_InvalidLogOn {
            get {
                return ResourceManager.GetString("ShopMonitor_ShopMonitorAuthenticator_InvalidLogOn", resourceCulture);
            }
        }
    }
}
